### ISSUE TITLE
Install sonar-scanner and build-wrapper step fails

### ISSUE THREAD

**Issue by HabibChaouach** [SonarSource/sonarqube-github-c-cpp#6]
Hello,

I recently wanted to integrate the Sonarqube scan for my C++ project however, I am not able to go past the step '**Install sonar-scanner and build-wrapper**'.
It fails while downloading the build wrapper.
Below is a screenshot of the issue:
<img width="1237" alt="image" src="https://github.com/SonarSource/sonarqube-github-c-cpp/assets/36036946/ac5cda47-542f-449e-b56a-48db79fafa65">

**Comment by rast01** [comment]
I've got the same problem. Any updates?

**Comment by HabibChaouach** [comment]
hello @claire-villard-sonarsource , @geoffray-adde-sonarsource @enzo-pellegrini , do you recognise this issue please and do you have any updates?

**Comment by enzo-pellegrini** [comment]
Hi, if you are still facing issues please reach out via our [Community](https://community.sonarsource.com/).

**Comment by agigleux** [comment]
This action works only if you have a SonarQube Developer Edition. If you don't have this version, I suggest looking at SonarCloud.io and the corresponding action: https://github.com/SonarSource/sonarcloud-github-c-cpp

As said by @enzo-pellegrini, if you are still facing issues, please post on the [SonarSource Community Forum](https://community.sonarsource.com/) with the tag "sonarqube".

We will close shortly the Issues tab on this repo.
